spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.42.111:3307/springboot_db?serverTimezone=GMT%2B8
    username: root
    password: root
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mapping/*.xml
# logging path和name只有一个生效，name优先级高
#logging:
#  file:
#    path: E:\\log\\wxj.log
#    name: E:\\log\\wxj.log